routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/'         , 'page/frontend/index')->name('index');
Route::view('register'  , 'page/frontend/register')->name('register');
Route::view('login'     , 'page/frontend/login')->name('login');
Route::view('gold'      , 'page/frontend/gold')->name('gold');
Route::view('download'  , 'page/frontend/download')->name('download');
Route::view('promotion' , 'page/frontend/promotion')->name('promotion');
Route::view('contact'   , 'page/frontend/contact')->name('contact');

Route::namespace('Auth')->prefix('backend')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login-backend');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::middleware('auth')->prefix('backend')->group(function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PUT('update', 'ProfileController@update')->name('profile.update');
    });

    Route::PATCH('sequence/up',   'SequenceController@up');
    Route::PATCH('sequence/down', 'SequenceController@down');

    Route::resource('role'      , 'RoleController');
    Route::resource('user'      , 'UserController');
    Route::resource('page'      , 'PageController');
    Route::resource('banner'    , 'BannerController');
    Route::resource('promotion' , 'PromotionController');
    Route::resource('gold'      , 'GoldController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Spatie\Permission\Models\Role;
use DB;

class UserController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:user-list');
        $this->middleware('permission:user-create', ['only' => ['create','store']]);
        $this->middleware('permission:user-edit'  , ['only' => ['edit','update']]);
        $this->middleware('permission:user-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        $user = User::all();
        return view('page.backend.user.index')->withItems($user);
    }

    public function create()
    {
        $roles = Role::pluck('name','name')->all();
        return view('page.backend.user.create')->with(['roles' => $roles]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'     => 'required',
            'username' => 'required|unique:users',
            'email'    => 'required|email|unique:users,email',
            'password' => 'confirmed',
            'roles'    => 'required'
        ]);

        $user           = new User;
        $user->name     = $request->name;
        $user->email    = $request->email;
        $user->username = $request->username;
        $user->password = $request->password;
        $user->save();
        $user->assignRole($request->input('roles'));

        return redirect()->route('user.index')->with('success','Success');
    }

    public function show(User $user)
    {
        return view('page.backend.user.show')->withUser($user);
    }

    public function edit(User $user)
    {
        $roles = Role::pluck('name','name')->all();
        $userRole = $user->roles->pluck('name','name')->all();
        return view('page.backend.user.edit')->with(['user' => $user, 'roles' => $roles, 'userRole' => $userRole]);
    }

    public function update(Request $request, User $user)
    {
        $message = [
            'username.required'  => 'กรุณากรอกชื่อผู้ใช้งาน',
            'username.unique'    => 'มีชื่อผู้ใช้งานในระบบแล้ว',
            'password.confirmed' => 'รหัสยืนยันไม่ตรงกัน',
            'email.required'     => 'กรุณากรอกอีเมล์',
            'email.unique'       => 'มีผู้ใช้อีเมล์นี้แล้ว',
        ];

        $request->validate([
            'name'     => 'required',
            'username' => 'required|min:6|max:30|unique:users,username,'.$user->id,
            'password' => 'confirmed',
            'email'    => 'required|email|unique:users,email,'.$user->id,
        ], $message);

        $user->name       = $request->name;
        $user->username   = $request->username;
        $user->password   = $request->password ? $request->password : $user->password;
        $user->email      = $request->email;
        $user->save();
        DB::table('model_has_roles')->where('model_id',$user->id)->delete();
        $user->assignRole($request->input('roles'));

        return redirect()->route('user.index')->with('update','Success');
    }

    public function destroy($id)
    {
        User::destroy($id);
        return redirect()->route('user.index')->with('delete','Successfully');
    }
}

resources/views/page/backend/user/create.blade.php
@extends('layouts.cms')
@section('title', 'เพิ่มผู้ใช้งาน')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-user-tie', 'name' => 'เพิ่มผู้ใช้งาน'])
<div class="content">
    <form action="{{ route('user.store') }}" method="POST" id="FormValidation">
        @csrf
        <div class="card">
            <div class="card-header header-elesments-inline">
                <legend class="text-uppercase font-size-sm font-weight-bold font f-20"> รายละเอียดผู้ใช้งาน </legend>
            </div>
            <div class="card-body">
                <fieldset class="mb-2">
                    <div class="form-group row">
                        <label for="name" class="col-form-label col-lg-2 font">ชื่อ</label>
                        <div class="col-lg-10">
                            <input type="text" name="name" class="form-control" placeholder="ชื่อ">
                            @if ($errors->has('name'))
                                <span class="form-text text-danger"> {{ $errors->first('name') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="username" class="col-form-label col-lg-2 font">ชื่อเข้าสู่ระบบ</label>
                        <div class="col-lg-10">
                            <input type="text" name="username" class="form-control" placeholder="ชื่อเข้าสู่ระบบ">
                            @if ($errors->has('username'))
                                <span class="form-text text-danger"> {{ $errors->first('username') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-form-label col-lg-2 font">รหัสผ่าน</label>
                        <div class="col-lg-10">
                            <input class="form-control" placeholder="รหัสผ่าน" type="password" name="password">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password_confirmation" class="col-form-label col-lg-2 font">ยืนยันรหัสผ่าน</label>
                        <div class="col-lg-10">
                            <input class="form-control" placeholder="ยืนยันรหัสผ่าน" type="password" name="password_confirmation">
                            @if ($errors->has('password'))
                            <span class="form-text text-danger"> {{ $errors->first('password') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-form-label col-lg-2 font">อีเมล์</label>
                        <div class="col-lg-10">
                            <input type="email" name="email" class="form-control" placeholder="อีเมล์">
                            @if ($errors->has('email'))
                                <span class="form-text text-danger"> {{ $errors->first('email') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="roles" class="col-form-label col-lg-2 font">สิทธิ์ผู้ใช้งาน</label>
                        <div class="col-lg-10">
                            <select name="roles[]" class="form-control" multiple>
                                @foreach ($roles as $rs)
                                    <option value="{{ $rs }}"> {{ $rs }} </option>
                                @endforeach
                            </select>
                            @if ($errors->has('roles'))
                                <span class="form-text text-danger"> {{ $errors->first('roles') }} </span>
                            @endif
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

@push('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function(e) {
            const form = document.getElementById('FormValidation');
            const fv = FormValidation.formValidation(
            form,
                {
                    fields: {
                        username: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกชื่อผู้ใช้งาน'
                                },
                                stringLength: {
                                    min: 6,
                                    max: 30,
                                    message: 'กรุณากรอกตัวอักษรระหว่าง 6 ถึง 30 ตัวอักษร'
                                }
                            }
                        },
                        password: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกพาสเวิร์ด'
                                },
                            }
                        },
                        password_confirmation: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกพาสเวิร์ดยืนยัน'
                                },
                                identical: {
                                    compare: function() {
                                        return form.querySelector('[name="password"]').value;
                                    },
                                    message: 'พาสเวิร์ดยืนยันไม่ตรงกัน'
                                }
                            }
                        },
                        email: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกอีเมล์'
                                },
                            }
                        },
                        roles: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณาเลือกสิทธิ์ผู้ใช้งาน'
                                },
                            }
                        },
                    },
                    plugins: {
                        trigger: new FormValidation.plugins.Trigger(),
                        bootstrap: new FormValidation.plugins.Bootstrap(),
                        submitButton: new FormValidation.plugins.SubmitButton(),
                        defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                        icon: new FormValidation.plugins.Icon({
                            valid: 'icon-checkmark2',
                            invalid: 'icon-cross3',
                            validating: 'icon-spinner9'
                        }),
                    },
                }
            );
        });
    </script>
@endpush

resources/views/page/backend/user/edit.blade.php
@extends('layouts.cms')
@section('title', 'แก้ไขผู้ใช้งาน')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-user-tie', 'name' => 'แก้ไขผู้ใช้งาน'])
<div class="content">
    <form action="{{ route('user.update', $user->id) }}" method="POST" id="FormValidation">
        @method('PUT')
        @csrf
        <div class="card">
            <div class="card-header header-elesments-inline">
                <legend class="text-uppercase font-size-sm font-weight-bold font f-20"> รายละเอียดผู้ใช้งาน </legend>
            </div>
            <div class="card-body">
                <fieldset class="mb-2">
                    <div class="form-group row">
                        <label for="name" class="col-form-label col-lg-2 font">ชื่อ</label>
                        <div class="col-lg-10">
                            <input type="text" name="name" class="form-control" placeholder="ชื่อ" value="{{ $user->name }}">
                            @if ($errors->has('name'))
                                <span class="form-text text-danger"> {{ $errors->first('name') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="username" class="col-form-label col-lg-2 font">ชื่อเข้าสู่ระบบ</label>
                        <div class="col-lg-10">
                            <input type="text" name="username" class="form-control" placeholder="ชื่อเข้าสู่ระบบ" value="{{ $user->username }}">
                            @if ($errors->has('username'))
                                <span class="form-text text-danger"> {{ $errors->first('username') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-form-label col-lg-2 font">รหัสผ่าน</label>
                        <div class="col-lg-10">
                            <input class="form-control" placeholder="รหัสผ่าน" type="password" name="password">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password_confirmation" class="col-form-label col-lg-2 font">ยืนยันรหัสผ่าน</label>
                        <div class="col-lg-10">
                            <input class="form-control" placeholder="ยืนยันรหัสผ่าน" type="password" name="password_confirmation">
                            @if ($errors->has('password'))
                            <span class="form-text text-danger"> {{ $errors->first('password') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-form-label col-lg-2 font">อีเมล์</label>
                        <div class="col-lg-10">
                            <input type="email" name="email" class="form-control" placeholder="อีเมล์" value="{{ $user->email }}">
                            @if ($errors->has('email'))
                                <span class="form-text text-danger"> {{ $errors->first('email') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="roles" class="col-form-label col-lg-2 font">สิทธิ์ผู้ใช้งาน</label>
                        <div class="col-lg-10">
                            <select name="roles[]" class="form-control" multiple>
                                @foreach ($roles as $rs)
                                    @if(in_array($rs, $userRole))
                                    <option value="{{ $rs }}" selected> {{ $rs }} </option>
                                    @else
                                    <option value="{{ $rs }}"> {{ $rs }} </option>
                                    @endif
                                @endforeach
                            </select>
                            @if ($errors->has('roles'))
                                <span class="form-text text-danger"> {{ $errors->first('roles') }} </span>
                            @endif
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

@push('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function(e) {
            const form = document.getElementById('FormValidation');
            const fv = FormValidation.formValidation(
            form,
                {
                    fields: {
                        username: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกชื่อผู้ใช้งาน'
                                },
                                stringLength: {
                                    min: 6,
                                    max: 30,
                                    message: 'กรุณากรอกตัวอักษรระหว่าง 6 ถึง 30 ตัวอักษร'
                                }
                            }
                        },
                        password_confirmation: {
                            validators: {
                                identical: {
                                    compare: function() {
                                        return form.querySelector('[name="password"]').value;
                                    },
                                    message: 'พาสเวิร์ดยืนยันไม่ตรงกัน'
                                }
                            }
                        },
                        email: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกอีเมล์'
                                },
                            }
                        },
                        roles: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณาเลือกสิทธิ์ผู้ใช้งาน'
                                },
                            }
                        },
                    },
                    plugins: {
                        trigger: new FormValidation.plugins.Trigger(),
                        bootstrap: new FormValidation.plugins.Bootstrap(),
                        submitButton: new FormValidation.plugins.SubmitButton(),
                        defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                        icon: new FormValidation.plugins.Icon({
                            valid: 'icon-checkmark2',
                            invalid: 'icon-cross3',
                            validating: 'icon-spinner9'
                        }),
                    },
                }
            );
        });
    </script>
@endpush

resources/views/page/backend/user/index.blade.php
@extends('layouts.cms')
@section('title', 'User | ผู้ใช้งาน')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-user-tie', 'name' => 'ผู้ใช้งาน'])
<!-- Content area -->
<div class="content">
    <!-- Hover rows -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title font f-22"> ผู้ใช้งาน </h5>
            @can('user-create')
            <a href="{{ route('user.create') }}" class="btn alpha-blue text-blue-800 border-blue-600 font" style="font-size:18px">
                <i class="icon-user-plus mr-2"></i> เพิ่มผู้ใช้งาน
            </a>
            @endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped datatable-user">
                    <thead>
                        <tr class="bg-slate-600 text-center">
                            <th class="text-center">#</th>
                            <th>ชื่อ</th>
                            <th>ชื่อเข้าใช้งาน</th>
                            <th>อีเมล์</th>
                            <th>กระทำ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($items as $k => $rs)
                        <tr>
                            <td class="text-center">{{ ++$k }}</td>
                            <td>{{ $rs->name }}</td>
                            <td>{{ $rs->username }}</td>
                            <td>{{ $rs->email }}</td>
                            <td class="text-center">
                                @include('template.backend.pattern.action', ['name' => 'user', 'id' => $rs->id])
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
    <!-- /hover rows -->
</div>
<!-- /content area -->
@endsection

@push('scripts')
<script>
$('.datatable-user').DataTable({
    columnDefs: [{
        orderable: false,
        targets: [4]
    }],
    dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"p>',
    language: {
        search: '<span>ค้นหา : </span> _INPUT_',
        lengthMenu: '<span>แสดง : </span> _MENU_',
        paginate: { 'first': 'First', 'last': 'Last', 'next': $('html').attr('dir') == 'rtl' ? '&larr;' : '&rarr;', 'previous': $('html').attr('dir') == 'rtl' ? '&rarr;' : '&larr;' }
    }
});

$('.btn-del').on('click',function(){
    let id = $(this).data('id');
    swal({
        title: "Are you sure?",
        text: "ต้องการที่จะลบ ผู้ใช้งาน นี้ใช่หรือไม่ !!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
    })
    .then((willDelete) => {
        if (willDelete) {
            $( "#delete-"+id ).submit();
        }
    });
});
</script>
@endpush

resources/views/page/backend/user/show.blade.php
@extends('layouts.cms')
@section('title', 'ข้อมูลผู้ใช้ระบบ')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-user-tie','name' => 'ข้อมูลผู้ใช้ระบบ'])
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body border-top-info">
                <h6 class="mb-3 font-weight-semibold font f-22"> รายละเอียดผู้ใช้ระบบ </h6>
                <p class="mb-3 text-muted"> User Description. </p>
                <div class="card card-body bg-light mb-0">
                    <dl class="row mb-0">
                        <dt class="col-lg-2 col-xs-5 font"> <b> ชื่อ </b>  </dt>
                        <dd class="col-lg-4 col-xs-7"> {{ $user->name }}</dd>

                        <dt class="col-lg-2 col-xs-5 font"> <b> ชื่อเข้าใช้ระบบ </b>  </dt>
                        <dd class="col-lg-4 col-xs-7"> {{ $user->username }}</dd>

                        <dt class="col-lg-2 col-xs-5 font"> <b> อีเมล์ </b>  </dt>
                        <dd class="col-lg-4 col-xs-7"> {{ $user->email }}</dd>

                        <dt class="col-lg-2 col-xs-5 font"> <b> สิทธิ์การเข้าใช้งาน </b>  </dt>
                        <dd class="col-lg-4 col-xs-7">
                            <p class="text-muted">
                                @if(!empty($user->getRoleNames()))
                                  @foreach($user->getRoleNames() as $v)
                                      <label class="badge badge-success"> {{ $v }} </label>
                                  @endforeach
                                @endif
                              </p>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection