routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/'         , 'page/frontend/index')->name('index');
Route::view('register'  , 'page/frontend/register')->name('register');
Route::view('login'     , 'page/frontend/login')->name('login');
Route::view('gold'      , 'page/frontend/gold')->name('gold');
Route::view('download'  , 'page/frontend/download')->name('download');
Route::view('promotion' , 'page/frontend/promotion')->name('promotion');
Route::view('contact'   , 'page/frontend/contact')->name('contact');

Route::namespace('Auth')->prefix('backend')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login-backend');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::middleware('auth')->prefix('backend')->group(function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PUT('update', 'ProfileController@update')->name('profile.update');
    });

    Route::PATCH('sequence/up',   'SequenceController@up');
    Route::PATCH('sequence/down', 'SequenceController@down');

    Route::resource('role'      , 'RoleController');
    Route::resource('user'      , 'UserController');
    Route::resource('page'      , 'PageController');
    Route::resource('banner'    , 'BannerController');
    Route::resource('promotion' , 'PromotionController');
    Route::resource('gold'      , 'GoldController');
});

app/Models/Gold.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Gold extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/GoldController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gold;
use Illuminate\Http\Request;
use File;

class GoldController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:gold-list');
        $this->middleware('permission:gold-create', ['only' => ['create','store']]);
        $this->middleware('permission:gold-edit'  , ['only' => ['edit','update']]);
        $this->middleware('permission:gold-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        return view('page.backend.gold.index')
        ->withItems(Gold::orderBy('sequence')->get())
        ->withMax(Gold::max('sequence'))
        ->withMin(Gold::min('sequence'));
    }

    public function create()
    {
        return view('page.backend.gold.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'      => 'required',
            'condition' => 'required',
            'image'     => 'mimes:jpeg,jpg,png'
        ]);

        $gold = new Gold;
        $gold->sequence  = Gold::max('sequence') + 1;
        $gold->name      = $request->name;
        $gold->condition = $request->condition;
        $gold->image     = $request->hasFile('image') ? uploadImage(['name' => 'gold', 'image' => $request->image, 'edit_image' => NULL]) : "no_image.png";
        $gold->save();
        return redirect()->route('gold.index')->with('success','Success');
    }

    public function show(Gold $gold)
    {
        return view('page.backend.gold.show')->withGold($gold);
    }

    public function edit(Gold $gold)
    {
        return view('page.backend.gold.edit')->withGold($gold);
    }

    public function update(Request $request, Gold $gold)
    {
        $request->validate([
            'name'      => 'required',
            'condition' => 'required',
            'image'     => 'mimes:jpeg,jpg,png'
        ]);
        $gold->name      = $request->name;
        $gold->condition = $request->condition;
        $gold->image     = $request->hasFile('image') ? uploadImage(['name' => 'gold', 'image' => $request->image, 'edit_image' => $request->edit_image]) : "no_image.png";
        $gold->save();
        return redirect()->route('gold.index')->with('success','Success');
    }

    public function destroy(Gold $gold)
    {
        File::delete('images/gold/'.$gold->image);
        Gold::destroy($gold->id);
        return redirect()->route('gold.index')->with('delete','Success');
    }
}

resources/views/page/backend/gold/create.blade.php
@extends('layouts.cms')
@section('title', 'เพิ่มเบอร์ทอง')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-list-numbered', 'name' => 'เพิ่มเบอร์ทอง'])
<div class="content">
    <form action="{{ route('gold.store') }}" method="POST" id="FormValidation" enctype="multipart/form-data">
        @csrf
        <div class="card">
            <div class="card-header header-elesments-inline">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดเบอร์ทอง
                    <span class="float-right">
                        <img src="/images/gold/no_image.png" width="60" height="60" class="rounded" id="photo">
                    </span>
                </legend>
            </div>
            <div class="card-body">
                <fieldset class="mb-2">
                    <div class="form-group row">
                        <label for="name" class="col-form-label col-lg-2 font">ชื่อ</label>
                        <div class="col-lg-10">
                            <input type="text" name="name" class="form-control" placeholder="ชื่อ">
                            @if ($errors->has('name'))
                                <span class="form-text text-danger"> {{ $errors->first('name') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="condition" class="col-form-label col-lg-2 font">เงื่อนไข</label>
                        <div class="col-lg-10">
                            <input type="text" name="condition" class="form-control" placeholder="เงื่อนไข">
                            @if ($errors->has('condition'))
                                <span class="form-text text-danger"> {{ $errors->first('condition') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-form-label col-lg-2 font"> รูปภาพ </label>
                        <div class="col-lg-10">
                            <input class="form-control" type="file" name="image" id="ActiveImage">
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

@push('scripts')
    <script>
        function readImage(input) {
            if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#photo').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
            }
        }

        $("#ActiveImage").change(function() {
            readImage(this);
        });

        document.addEventListener('DOMContentLoaded', function(e) {
            const form = document.getElementById('FormValidation');
            const fv = FormValidation.formValidation(
            form,
                {
                    fields: {
                        name: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกชื่อ'
                                }
                            }
                        },
                        condition: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกเงื่อนไข'
                                },
                            }
                        },
                        image: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณาเลือกรูปภาพ'
                                },
                                file: {
                                    extension: 'jpeg,jpg,png',
                                    type: 'image/jpeg,image/png',
                                    message: 'กรุณาเลือกไฟล์รูปภาพ'
                                }
                            }
                        }
                    },
                    plugins: {
                        trigger: new FormValidation.plugins.Trigger(),
                        bootstrap: new FormValidation.plugins.Bootstrap(),
                        submitButton: new FormValidation.plugins.SubmitButton(),
                        defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                        icon: new FormValidation.plugins.Icon({
                            valid: 'icon-checkmark2',
                            invalid: 'icon-cross3',
                            validating: 'icon-spinner9'
                        }),
                    },
                }
            );
        });
    </script>
@endpush

resources/views/page/backend/gold/edit.blade.php
@extends('layouts.cms')
@section('title', 'แก้ไขเบอร์ทอง')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-list-numbered', 'name' => 'แก้ไขเบอร์ทอง'])
<div class="content">
    <form action="{{ route('gold.update', $gold->id) }}" method="POST" id="FormValidation" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <input type="hidden" value="{{ $gold->image }}" name="edit_image">
        <div class="card">
            <div class="card-header header-elesments-inline">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดเบอร์ทอง
                    <span class="float-right">
                        <img src="/images/gold/{{$gold->image}}" width="60" height="60" class="rounded" id="photo">
                    </span>
                </legend>
            </div>
            <div class="card-body">
                <fieldset class="mb-2">
                    <div class="form-group row">
                        <label for="name" class="col-form-label col-lg-2 font">ชื่อ</label>
                        <div class="col-lg-10">
                            <input type="text" name="name" class="form-control" placeholder="ชื่อ" value="{{ $gold->name }}">
                            @if ($errors->has('name'))
                                <span class="form-text text-danger"> {{ $errors->first('name') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="condition" class="col-form-label col-lg-2 font">เงื่อนไข</label>
                        <div class="col-lg-10">
                            <input type="text" name="condition" class="form-control" placeholder="เงื่อนไข" value="{{ $gold->condition }}">
                            @if ($errors->has('condition'))
                                <span class="form-text text-danger"> {{ $errors->first('condition') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-form-label col-lg-2 font"> รูปภาพ </label>
                        <div class="col-lg-10">
                            <input class="form-control" type="file" name="image" id="ActiveImage">
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

@push('scripts')
    <script>
        function readImage(input) {
            if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#photo').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
            }
        }

        $("#ActiveImage").change(function() {
            readImage(this);
        });

        document.addEventListener('DOMContentLoaded', function(e) {
            const form = document.getElementById('FormValidation');
            const fv = FormValidation.formValidation(
            form,
                {
                    fields: {
                        name: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกชื่อ'
                                }
                            }
                        },
                        condition: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกเงื่อนไข'
                                },
                            }
                        },
                        image: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณาเลือกรูปภาพ'
                                },
                                file: {
                                    extension: 'jpeg,jpg,png',
                                    type: 'image/jpeg,image/png',
                                    message: 'กรุณาเลือกไฟล์รูปภาพ'
                                }
                            }
                        }
                    },
                    plugins: {
                        trigger: new FormValidation.plugins.Trigger(),
                        bootstrap: new FormValidation.plugins.Bootstrap(),
                        submitButton: new FormValidation.plugins.SubmitButton(),
                        defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                        icon: new FormValidation.plugins.Icon({
                            valid: 'icon-checkmark2',
                            invalid: 'icon-cross3',
                            validating: 'icon-spinner9'
                        }),
                    },
                }
            );
        });
    </script>
@endpush

resources/views/page/backend/gold/index.blade.php
@extends('layouts.cms')
@section('title', 'Gold | เบอร์ทอง')
@section('content')
@include('template.backend.header',['icon'=> 'icon-list-numbered', 'name' => 'เบอร์ทอง'])
<div class="content">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title font"> ข้อมูลเบอร์ทอง </h5>
            @can('gold-create')
            <a href="{{ route('gold.create') }}" class="btn alpha-blue text-blue-800 border-blue-600 font" style="font-size:18px">
                <i class="icon-plus2 mr-2"></i> เพิ่มเบอร์ทอง
            </a>
            @endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped datatable-gold">
                    <thead>
                        <tr class="bg-slate-600 text-center">
                            <th class="text-center">#</th>
                            <th>ลำดับ</th>
                            <th>ชื่อ</th>
                            <th>เงื่อนไข</th>
                            <th>รูปภาพ</th>
                            <th>กระทำ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($items as $k => $rs)
                        <tr>
                            <td class="text-center">{{ ++$k }}</td>
                            <td class="text-center" width="20%">
                               @include('template.backend.pattern.sequence', ['name' => 'gold', 'sequence' => $rs->sequence, 'min' => $min, 'max' => $max])
                            </td>
                            <td class="text-center">{{ $rs->name }}</td>
                            <td class="text-left">{{ $rs->condition }}</td>
                            <td class="text-center">
                                <img src="/images/gold/{{ $rs->image }}" alt="" width="80" height="80" class="img-responsive">
                            </td>
                            <td class="text-center">
                                @include('template.backend.pattern.action', ['name' => 'gold', 'id' => $rs->id])
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$('.datatable-gold').DataTable({
    columnDefs: [{
        orderable: false,
        targets: [1,4,5]
    }],
    dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"p>',
    language: {
        search: '<span>ค้นหา : </span> _INPUT_',
        lengthMenu: '<span>แสดง : </span> _MENU_',
        paginate: { 'first': 'First', 'last': 'Last', 'next': $('html').attr('dir') == 'rtl' ? '&larr;' : '&rarr;', 'previous': $('html').attr('dir') == 'rtl' ? '&rarr;' : '&larr;' }
    }
});

$('.btn-del').on('click',function(){
    let id = $(this).data('id');
    swal({
        title: "Are you sure?",
        text: "ต้องการที่จะลบ เบอร์ทอง นี้ใช่หรือไม่ !!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
    })
    .then((willDelete) => {
        if (willDelete) {
            $( "#delete-"+id ).submit();
        }
    });
});

$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

$('.up').on('click',function(){
    let no   = $(this).data('no');
    let name = $(this).data('name');

    $.ajax({
        type: "PATCH",
        url: "/backend/sequence/up",
        data: {no : no, name : name},
        success: function(rs){
            swal("Success!", "ทำการเลื่อนตำแหน่งเรียบร้อยแล้ว", "success", {button:false});
            setTimeout(function() {
                location.reload();
            }, 1200);
		}
	});
});

$('.down').on('click',function(){
    let no   = $(this).data('no');
    let name = $(this).data('name');
    $.ajax({
        type: "PATCH",
        url: "/backend/sequence/down",
        data: {no : no, name : name},
        success: function(rs){
            swal("Success!", "ทำการเลื่อนตำแหน่งเรียบร้อยแล้ว", "success",{button:false});
            setTimeout(function() {
                location.reload();
            }, 1200);
		}
	});
});
</script>
@endpush

resources/views/page/backend/gold/show.blade.php
@extends('layouts.cms')
@section('title', 'รายละเอียดเบอร์ทอง')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-list-numbered', 'name' => 'รายละเอียดเบอร์ทอง'])
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body border-top-info">
                <h6 class="mb-3 font-weight-semibold font f-22">
                    รายละเอียดเบอร์ทอง
                </h6>
                <div class="card">
                    <div class="card-body text-center">
                        <h6 class="font-weight-semibold mb-0 font f-22"> <strong> ชื่อ </strong> </h6>
                        <span class="d-block text-muted font f-20"> {{ $gold->name }} </span>
                        <h6 class="font-weight-semibold mb-0 font f-22 mt-2"> <strong> เงื่อนไข </strong> </h6>
                        <span class="d-block text-muted font f-20"> {{ $gold->condition }} </span>
                    </div>
                </div>
                <div class="card card-body bg-light mt-3">
                    <dl class="row mb-0">
                        <dt class="col col-sm-12 font text-center">
                            <strong> รูปภาพ </strong>
                        </dt>
                        <dd class="col-sm-12 mt-3 pa-2">
                            <div class="row">
                                <div class="col-md-4 offset-md-4">
                                    <div class="card">
                                        <div class="card-img-actions m-1">
                                            <img class="card-img img-fluid" src="/images/gold/{{ $gold->image }}" alt="">
                                            <div class="card-img-actions-overlay card-img">
                                                <a href="/images/gold/{{ $gold->image }}" class="btn btn-outline bg-white text-white border-white border-2 btn-icon rounded-round" data-fancybox="images">
                                                    <i class="icon-enlarge7"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection