routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/'         , 'page/frontend/index')->name('index');
Route::view('register'  , 'page/frontend/register')->name('register');
Route::view('login'     , 'page/frontend/login')->name('login');
Route::view('gold'      , 'page/frontend/gold')->name('gold');
Route::view('download'  , 'page/frontend/download')->name('download');
Route::view('promotion' , 'page/frontend/promotion')->name('promotion');
Route::view('contact'   , 'page/frontend/contact')->name('contact');

Route::namespace('Auth')->prefix('backend')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login-backend');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::middleware('auth')->prefix('backend')->group(function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PUT('update', 'ProfileController@update')->name('profile.update');
    });

    Route::PATCH('sequence/up',   'SequenceController@up');
    Route::PATCH('sequence/down', 'SequenceController@down');

    Route::resource('role'      , 'RoleController');
    Route::resource('user'      , 'UserController');
    Route::resource('page'      , 'PageController');
    Route::resource('banner'    , 'BannerController');
    Route::resource('promotion' , 'PromotionController');
    Route::resource('gold'      , 'GoldController');
});

resources/views/page/backend/page/create.blade.php
@extends('layouts.cms')
@section('title', 'เพิ่มข้อมูลหน้า')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-stack-text', 'name' => 'เพิ่มข้อมูลหน้า'])
<div class="content">
    <form action="{{ route('page.store') }}" method="POST" id="FormValidation">
        @csrf
        <div class="card">
            <div class="card-header header-elesments-inline">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดข้อมูลหน้า
                </legend>
            </div>
            <div class="card-body">
                <fieldset class="mb-2">
                    <div class="form-group row">
                        <label for="name" class="col-form-label col-lg-2 font">ชื่อ</label>
                        <div class="col-lg-10">
                            <input type="text" name="name" class="form-control" placeholder="ชื่อ">
                            @if ($errors->has('name'))
                                <span class="form-text text-danger"> {{ $errors->first('name') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font">หน้า</label>
                        <div class="col-lg-10">
                            <input type="text" name="page" class="form-control" placeholder="หน้า">
                            @if ($errors->has('page'))
                                <span class="form-text text-danger"> {{ $errors->first('page') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font">สถานะ</label>
                        <div class="col-lg-10">
                            <div class="form-check form-check-inline mb-4">
                                <label class="form-check-label">
                                    <input type="radio" name="active" class="form-check-input-styled-primary" value="1">
                                    Active
                                </label>
                            </div>
                            <div class="form-check form-check-inline mb-4">
                                <label class="form-check-label">
                                    <input type="radio" name="active" class="form-check-input-styled-primary" value="0" checked>
                                    InActive
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font"> Title </label>
                        <div class="col-lg-10">
                            <input type="text" name="title" class="form-control" placeholder="Title">
                            @if ($errors->has('title'))
                                <span class="form-text text-danger"> {{ $errors->first('title') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font"> Description </label>
                        <div class="col-lg-10">
                            <textarea name="description" cols="30" rows="10" placeholder="Description" class="form-control"></textarea>
                            @if ($errors->has('description'))
                                <span class="form-text text-danger"> {{ $errors->first('description') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font"> Keywords </label>
                        <div class="col-lg-10">
                            <textarea name="keywords" cols="30" rows="10" placeholder="Keywords" class="form-control"></textarea>
                            @if ($errors->has('keywords'))
                                <span class="form-text text-danger"> {{ $errors->first('keywords') }} </span>
                            @endif
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

@push('scripts')
    <script src="{{ asset('template/plugins/uniform/uniform.min.js') }}"></script>
    <script>
        $('.form-check-input-styled-primary').uniform({
            wrapperClass: 'border-primary-600 text-primary-800'
        });
        document.addEventListener('DOMContentLoaded', function(e) {
            const form = document.getElementById('FormValidation');
            const fv = FormValidation.formValidation(
            form,
                {
                    fields: {
                        name: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกชื่อ'
                                }
                            }
                        },
                        page: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกหน้า'
                                }
                            }
                        },
                        title: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอก title'
                                }
                            }
                        },
                        description: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอก description'
                                }
                            }
                        },
                        keywords: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอก keywords'
                                }
                            }
                        },
                    },
                    plugins: {
                        trigger: new FormValidation.plugins.Trigger(),
                        bootstrap: new FormValidation.plugins.Bootstrap(),
                        submitButton: new FormValidation.plugins.SubmitButton(),
                        defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                        icon: new FormValidation.plugins.Icon({
                            valid: 'icon-checkmark2',
                            invalid: 'icon-cross3',
                            validating: 'icon-spinner9'
                        }),
                    },
                }
            );
        });
    </script>
@endpush

resources/views/page/backend/page/edit.blade.php
@extends('layouts.cms')
@section('title', 'แก้ไขข้อมูลหน้า')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-stack-text', 'name' => 'แก้ไขข้อมูลหน้า'])
<div class="content">
    <form action="{{ route('page.update', $page->id) }}" method="POST" id="FormValidation">
        @method('PUT')
        @csrf
        <div class="card">
            <div class="card-header header-elesments-inline">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดข้อมูลหน้า
                </legend>
            </div>
            <div class="card-body">
                <fieldset class="mb-2">
                    <div class="form-group row">
                        <label for="name" class="col-form-label col-lg-2 font">ชื่อ</label>
                        <div class="col-lg-10">
                            <input type="text" name="name" class="form-control" placeholder="ชื่อ" value="{{ $page->name }}">
                            @if ($errors->has('name'))
                                <span class="form-text text-danger"> {{ $errors->first('name') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font">หน้า</label>
                        <div class="col-lg-10">
                            <input type="text" name="page" class="form-control" placeholder="หน้า" value="{{ $page->page }}">
                            @if ($errors->has('page'))
                                <span class="form-text text-danger"> {{ $errors->first('page') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font">สถานะ </label>
                        <div class="col-lg-10">
                            <div class="form-check form-check-inline mb-4">
                                <label class="form-check-label">
                                    <input type="radio" name="active" class="form-check-input-styled-primary" value="1" {{ $page->active == 1 ? 'checked' : '' }}>
                                    Active
                                </label>
                            </div>
                            <div class="form-check form-check-inline mb-4">
                                <label class="form-check-label">
                                    <input type="radio" name="active" class="form-check-input-styled-primary" value="0" {{ $page->active == 0 ? 'checked' : '' }}>
                                    InActive
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font"> Title </label>
                        <div class="col-lg-10">
                            <input type="text" name="title" class="form-control" placeholder="Title" value="{{ $page->title }}">
                            @if ($errors->has('title'))
                                <span class="form-text text-danger"> {{ $errors->first('title') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font"> Description </label>
                        <div class="col-lg-10">
                            <textarea name="description" cols="30" rows="10" placeholder="Description" class="form-control">{{ $page->description }}</textarea>
                            @if ($errors->has('description'))
                                <span class="form-text text-danger"> {{ $errors->first('description') }} </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row ">
                        <label for="page" class="col-form-label col-lg-2 font"> Keywords </label>
                        <div class="col-lg-10">
                            <textarea name="keywords" cols="30" rows="10" placeholder="Keywords" class="form-control">{{ $page->keywords }}</textarea>
                            @if ($errors->has('keywords'))
                                <span class="form-text text-danger"> {{ $errors->first('keywords') }} </span>
                            @endif
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

@push('scripts')
<script src="{{ asset('template/plugins/uniform/uniform.min.js') }}"></script>
<script>
        $('.form-check-input-styled-primary').uniform({
            wrapperClass: 'border-primary-600 text-primary-800'
        });
        document.addEventListener('DOMContentLoaded', function(e) {
            const form = document.getElementById('FormValidation');
            const fv = FormValidation.formValidation(
              form,
                {
                    fields: {
                        name: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกชื่อ'
                                }
                            }
                        },
                        page: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอกหน้า'
                                }
                            }
                        },
                        title: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอก title'
                                }
                            }
                        },
                        description: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอก description'
                                }
                            }
                        },
                        keywords: {
                            validators: {
                                notEmpty: {
                                    message: 'กรุณากรอก keywords'
                                }
                            }
                        },
                    },
                    plugins: {
                        trigger: new FormValidation.plugins.Trigger(),
                        bootstrap: new FormValidation.plugins.Bootstrap(),
                        submitButton: new FormValidation.plugins.SubmitButton(),
                        defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                        icon: new FormValidation.plugins.Icon({
                            valid: 'icon-checkmark2',
                            invalid: 'icon-cross3',
                            validating: 'icon-spinner9'
                        }),
                    },
                }
            );
        });
    </script>
@endpush

resources/views/page/backend/page/index.blade.php
@extends('layouts.cms')
@section('title', 'Page | ข้อมูลหน้า')
@section('content')
@include('template.backend.header',['icon'=> 'icon-stack-text', 'name' => 'ข้อมูลหน้า'])
<div class="content">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title font"> ข้อมูลหน้า </h5>
            @can('page-create')
            <a href="{{ route('page.create') }}" class="btn alpha-blue text-blue-800 border-blue-600 font" style="font-size:18px">
                <i class="icon-plus2 mr-2"></i> เพิ่มข้อมูลหน้า
            </a>
            @endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped datatable-table">
                    <thead>
                        <tr class="bg-slate-600 text-center">
                            <th class="text-center">#</th>
                            <th>ลำดับ</th>
                            <th>ชื่อ</th>
                            <th>หน้า</th>
                            <th>สถานะ</th>
                            <th>กระทำ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($items as $k => $rs)
                        <tr>
                            <td class="text-center">{{ ++$k }}</td>
                            <td class="text-center" width="20%">
                                @include('template.backend.pattern.sequence', ['name' => 'page', 'sequence' => $rs->sequence, 'min' => $min, 'max' => $max])
                             </td>
                            <td class="text-left">{{ $rs->name }}</td>
                            <td class="text-left">{{ $rs->page }}</td>
                            <td class="text-center">
                                @switch($rs->active)
                                    @case(0)
                                    <span class="badge bg-danger">ไม่แสดง</span>
                                    @break
                                    @case(1)
                                    <span class="badge bg-success">แสดง</span>
                                    @break
                                @endswitch
                            </td>
                            <td class="text-center">
                                @include('template.backend.pattern.action', ['name' => 'page', 'id' => $rs->id])
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$('.datatable-table').DataTable({
    columnDefs: [{
        orderable: false,
        targets: [4]
    }],
    dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"p>',
    language: {
        search: '<span>ค้นหา : </span> _INPUT_',
        lengthMenu: '<span>แสดง : </span> _MENU_',
        paginate: { 'first': 'First', 'last': 'Last', 'next': $('html').attr('dir') == 'rtl' ? '&larr;' : '&rarr;', 'previous': $('html').attr('dir') == 'rtl' ? '&rarr;' : '&larr;' }
    }
});
$('.btn-del').on('click',function(){
    let id = $(this).data('id');
    swal({
        title: "Are you sure?",
        text: "ต้องการที่จะลบ ข้อมูลหน้า นี้ใช่หรือไม่ !!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
    })
    .then((willDelete) => {
        if (willDelete) {
            $( "#delete-"+id ).submit();
        }
    });
});

$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

$('.up').on('click',function(){
    let no   = $(this).data('no');
    let name = $(this).data('name');
    $.ajax({
        type: "PATCH",
        url: "/backend/sequence/up",
        data: {no : no, name : name},
        success: function(rs){
            swal("Success!", "ทำการเลื่อนตำแหน่งเรียบร้อยแล้ว", "success", {button:false});
            setTimeout(function() {
                location.reload();
            }, 1200);
		}
	});
});

$('.down').on('click',function(){
    let no   = $(this).data('no');
    let name = $(this).data('name');
    $.ajax({
        type: "PATCH",
        url: "/backend/sequence/down",
        data: {no : no, name : name},
        success: function(rs){
            swal("Success!", "ทำการเลื่อนตำแหน่งเรียบร้อยแล้ว", "success",{button:false});
            setTimeout(function() {
                location.reload();
            }, 1200);
		}
	});
});
</script>
@endpush

resources/views/page/backend/page/show.blade.php
@extends('layouts.cms')
@section('title', 'รายละเอียดหน้า')
@section('content')
@include('template.backend.header', ['icon'=> 'icon-list-numbered', 'name' => 'รายละเอียดหน้า'])
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body border-top-info">
                <h6 class="mb-3 font-weight-semibold font f-22">
                    รายละเอียดหน้า
                </h6>
                <div class="card">
                    <div class="card-body text-center">
                        <h6 class="font-weight-semibold mb-0 font f-22"> <strong> ชื่อ </strong> </h6>
                        <span class="d-block text-muted font f-20"> {{ $page->name }} </span>
                        <h6 class="font-weight-semibold mb-0 font f-22 mt-2"> <strong> หน้า </strong> </h6>
                        <span class="d-block text-muted font f-20"> {{ $page->page }} </span>
                    </div>
                </div>
                <div class="card card-body bg-light mt-3">
                    <dl class="row mb-0">
                        <dt class="col col-sm-12 font text-center">
                            <strong> Title </strong>
                        </dt>
                        <dd class="col-sm-12 mt-3 pa-2">
                            <div class="row">
                                <div class="col-md-4 offset-md-4 text-center">
                                    <p>{!! $page->title !!}</p>
                                </div>
                            </div>
                        </dd>
                    </dl>
                    <br>
                    <dl class="row mb-0">
                        <dt class="col col-sm-12 font text-center">
                            <strong> Description </strong>
                        </dt>
                        <dd class="col-sm-12 mt-3 pa-2">
                            <div class="row">
                                <div class="col-md-4 offset-md-4 text-center">
                                    <p>{!! $page->description !!}</p>
                                </div>
                            </div>
                        </dd>
                    </dl>
                    <br>
                    <dl class="row mb-0">
                        <dt class="col col-sm-12 font text-center">
                            <strong> Keywords </strong>
                        </dt>
                        <dd class="col-sm-12 mt-3 pa-2">
                            <div class="row">
                                <div class="col-md-4 offset-md-4 text-center">
                                    <p>{!! $page->keywords !!}</p>
                                </div>
                            </div>
                        </dd>
                    </dl>
                    <br>
                    <dl class="row mb-0">
                        <dt class="col col-sm-12 font text-center">
                            <strong> Active </strong>
                        </dt>
                        <dd class="col-sm-12 mt-3 pa-2">
                            <div class="row">
                                <div class="col-md-4 offset-md-4 text-center">
                                    @switch($page->active)
                                        @case(0)
                                        <span class="badge bg-danger">ไม่แสดง</span>
                                        @break
                                        @case(1)
                                        <span class="badge bg-success">แสดง</span>
                                        @break
                                    @endswitch
                                </div>
                            </div>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection